package com.example.covid19.currencyFile;

public class CurrencyName {

        public static final String[] currencyCountry = {"(AED) United Arab Emirates Dirham", "(AFN) Afghan Afghani", "(ALL) Albanian Lek",
                "(AMD) Armenian Dram", "(ANG) Netherlands Antillean Guilder", "(AOA) Angolan Kwanza", "(ARS) Argentine Peso",
                "(AUD) Australian Dollar", "(AWG) Aruban Florin", "(AZN) Azerbaijani Manat", "(BAM) Bosnia-Herzegovina Convertible Mark",
                "(BBD) Barbadian Dollar", "(BDT) Bangladeshi Taka", "(BGN) Bulgarian Lev", "(BHD) Bahraini Dinar", "(BIF) Burundian Franc",
                "(BMD) Bermudan Dollar", "(BND) Brunei Dollar", "(BOB) Bolivian Boliviano", "(BRL) Brazilian Real", "(BSD) Bahamian Dollar" ,
                "(BTN) Bhutanese Ngultrum", "(BWP) Botswanan Pula", "(BZD) Belize Dollar", "(CAD) Canadian Dollar", "(CDF) Congolese Franc" ,
                "(CHF) Swiss Franc", "(CLF) Chilean Unit of Account UF", "(CLP) Chilean Peso", "(CNH) Chinese Yuan Offshore",
                "(CNY) Chinese Yuan", "(COP) Colombian Peso", "(CUP) Cuban Peso", "(CVE) Cape Verdean Escudo", "(CZK) Czech Republic Koruna" ,
                "(DJF) Djiboutian Franc", "(DKK) Danish Krone", "(DOP) Dominican Peso", "(DZD) Algerian Dinar", "(EGP) Egyptian Pound",
                "(ERN) Eritrean Nakfa", "(ETB) Ethiopian Birr", "(EUR) Euro", "(FJD) Fijian Dollar", "(FKP) Falkland Islands Pound" ,
                "(GBP) British Pound Sterling", "(GEL) Georgian Lari", "(GHS) Ghanaian Cedi", "(GIP) Gibraltar Pound", "(GMD) Gambian Dalasi" ,
                "(GNF) Guinean Franc", "(GTQ) Guatemalan Quetzal", "(GYD) Guyanaese Dollar", "(HKD) Hong Kong Dollar", "(HNL) Honduran Lempira" ,
                "(HRK) Croatian Kuna", "(HTG) Haitian Gourde", "(HUF) Hungarian Forint", "(IDR) Indonesian Rupiah", "(ILS) Israeli New Sheqel" ,
                "(INR) Indian Rupee", "(IQD) Iraqi Dinar", "(IRR) Iranian Rial", "(ISK) Icelandic Krona", "(JEP) Jersey Pound",
                "(JMD) Jamaican Dollar", "(JOD) Jordanian Dinar", "(JPY) Japanese Yen", "(KES) Kenyan Shilling", "(KGS) Kyrgystani Som" ,
                "(KHR) Cambodian Riel", "(KMF) Comorian Franc", "(KPW) North Korean Won", "(KRW) South Korean Won", "(KWD) Kuwaiti Dinar" ,
                "(KYD) Cayman Islands Dollar", "(KZT) Kazakhstani Tenge", "(LAK) Laotian Kip", "(LBP) Lebanese Pound", "(LKR) Sri Lankan Rupee" ,
                "(LRD) Liberian Dollar", "(LSL) Lesotho Loti", "(LYD) Libyan Dinar", "(MAD) Moroccan Dirham", "(MDL) Moldovan Leu" ,
                "(MGA) Malagasy Ariary", "(MKD) Macedonian Denar", "(MMK) Myanma Kyat", "(MNT) Mongolian Tugrik", "(MOP) Macanese Pataca",
                "(MRO) Mauritanian Ouguiya", "(MRU) Mauritanian Ouguiya", "(MUR) Mauritian Rupee", "(MVR) Maldivian Rufiyaa" ,
                "(MWK) Malawian Kwacha", "(MXN) Mexican Peso", "(MYR) Malaysian Ringgit", "(MZN) Mozambican Metical", "(NAD) Namibian Dollar",
                "(NGN) Nigerian Naira", "(NOK) Norwegian Krone", "(NPR) Nepalese Rupee", "(NZD) New Zealand Dollar", "(OMR) Omani Rial",
                "(PAB) Panamanian Balboa", "(PEN) Peruvian Nuevo Sol", "(PGK) Papua New Guinean Kina", "(PHP) Philippine Peso",
                "(PKR) Pakistani Rupee", "(PLN) Polish Zloty", "(PYG) Paraguayan Guarani", "(QAR) Qatari Rial", "(RON) Romanian Leu",
                "(RSD) Serbian Dinar", "(RUB) Russian Ruble", "(RUR) Old Russian Ruble", "(RWF) Rwandan Franc", "(SAR) Saudi Riyal",
                "(SBDf) Solomon Islands Dollar", "(SCR) Seychellois Rupee", "(SDG) Sudanese Pound", "(SEK) Swedish Krona",
                "(SGD) Singapore Dollar", "(SHP) Saint Helena Pound", "(SLL) Sierra Leonean Leone", "(SOS) Somali Shilling",
                "(SRD) Surinamese Dollar", "(SYP) Syrian Pound", "(SZL) Swazi Lilangeni", "(THB) Thai Baht", "(TJS) Tajikistani Somoni",
                "(TMT) Turkmenistani Manat", "(TND) Tunisian Dinar", "(TOP) Tongan Pa'anga", "(TRY) Turkish Lira", "(TTD) Trinidad and Tobago Dollar",
                "(TWD) New Taiwan Dollar", "(TZS) Tanzanian Shilling", "(UAH) Ukrainian Hryvnia", "(UGX) Ugandan Shilling", "(USD) United States Dollar" ,
                "(UYU) Uruguayan Peso", "(UZS) Uzbekistan Som", "(VND) Vietnamese Dong", "(VUV) Vanuatu Vatu", "(WST) Samoan Tala" ,
                "(XAF) CFA Franc BEAC", "(XAG) Silver Ounce", "(XAU) Gold Ounce", "(XCD) East Caribbean Dollar", "(XDR) Special Drawing Rights",
                "(XOF) CFA Franc BCEAO", "(XPF) CFP Franc", "(YER) Yemeni Rial", "(ZAR) South African Rand", "(ZMW) Zambian Kwacha",
                "(ZWL) Zimbabwean Dollar"};

        public static final String[] currencyCode = {"AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN",
                "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTN", "BWP", "BZD", "CAD", "CDF", "CHF", "CLF",
                "CLP", "CNH", "CNY", "COP", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP",
                "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK",
                "JEP", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL",
                "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRO", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN",
                "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RUR", "RWF", "SAR",
                "SBDf", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD",
                "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XCD", "XDR", "XOF", "XPF", "YER",
                "ZAR", "ZMW", "ZWL"};
}
